### ISSUE TITLE
Lanjut Terus yaann...!!

### ISSUE THREAD

**Issue by edwin** [rmage/gnvc-ims#1]
Hampir 30bulan, maju terus yan
Pantang menyerah..!!

![initialcommit](https://cloud.githubusercontent.com/assets/1367886/15985226/99325b2e-3010-11e6-9198-25abdf8ae34b.PNG)

**Comment by rmage** [comment]
hahaha ,
masih idup ini project makanya commit jalan terus,

**Comment by rmage** [comment]
hahaha ,
masih idup ini project makanya commit jalan terus,

**Comment by rmage** [comment]
hahaha ,
masih idup ini project makanya commit jalan terus,

**Comment by ilhamtifa** [comment]
Kangen jg sm kamu yan di Wisma Pelaut berdua.. Mati lampu lagi.. Hahaha

## 

Regards,
Teuku Ilham F. Akbar

**Comment by asmaraindra** [comment]
Hajar terus yan... Tetap semangat pantang menyerah.. Btw minal aidin walfaidzin yah.. Mohon maaf lahir dan batin semuanya..

Thanks & Regards,

Indra Asmara

**Comment by ilhamtifa** [comment]
Minal adizin wal faidzin jg ya bro.

Wahh banyak jg yg msh connect sm project ini ya.

## 

Regards,
Teuku Ilham F. Akbar

**Comment by faridzif** [comment]
Maaf lahir bathin yaa.

Masih active aja ini repo :))

**Comment by ariesfebrian** [comment]
Mohon maaf lahir dan batin juga ya semua.
Repo aktif terus jo, CR terus~ hahahaha..

Regards,

Aris Febrianto

Pada tanggal Jum, 15 Jul 2016 14.28 Faridzi Febrian <
notifications@github.com> menulis:

> Maaf lahir bathin yaa.
> 
> Masih active aja ini repo :))
> 
> Sent from my iPhone
>

**Comment by edwin** [comment]
Akwkakwkakw, ryan panen CR ni.
Bisa lah kita diajakin berenang bareng di Bunaken :D

---

sent from my mobile device.

**Comment by rmage** [comment]
crnya sepi bang,
lagi susah ikan ikannya :)
